/*
COPY THIS FILE AS WiFiConfig.h AND CHANGE THE FOLLOWING OPTIONS TO MATCH YOUR NETWORK.
*/

#ifndef _WIFI_CONFIG_H_
#define _WIFI_CONFIG_H_

// WIFI
#ifndef WIFI_DEFAULT_SSID
#define WIFI_DEFAULT_SSID "wifi_ssid"
#endif

#ifndef WIFI_DEFAULT_PASSWORD
#define WIFI_DEFAULT_PASSWORD "wifi_password"
#endif

#endif  // _WIFI_CONFIG_H_
